{% set name = "mgefinder" %}
{% set version = "0.0.1.dev7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "756cc195a03cfc17a0d550a000ad618957239b11f60de6813705772911ee2847"

build:
  number: 0
  entry_points:
    - mgefinder = mgefinder.main:cli
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - biopython
    - click
    - editdistance
    - pandas
    - pip
    - pysam
    - python
    - scipy
    - networkx
    - tqdm
    - snakemake
  run:
    - biopython
    - click
    - editdistance
    - pandas
    - pysam
    - python
    - scipy
    - networkx
    - tqdm
    - snakemake
    - samtools
    - htslib
    - emboss
    - bowtie2
    - bwa
    - cd-hit

test:
  imports:
    - mgefinder
  commands:
    - mgefinder --help

about:
  home: "https://github.com/bhattlab/MGEfinder"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "A toolbox for identifying mobile genetic element (MGE) insertions from short-read sequencing data of bacterial isolates."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - bhattlab
